blank_issues_enabled: true # blank issues enabled by default

contact_links:
  - name: GitHub Community Support
    url: https://links.dam450.dev/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://links.dam450.dev/
    about: Please report security vulnerabilities here.
